import httpx
import asyncio
import logging
from uuid import UUID
from sqlalchemy import delete, select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.db_models import AudioSegment, FrameVector, SimilarityResult

logger = logging.getLogger("sourcegraph.auditor_client")

AUDITOR_URL = "http://localhost:8004/api/v1/auditor"


def _uuid_or_none(value: object) -> UUID | None:
    if not value:
        return None
    try:
        return UUID(str(value))
    except (TypeError, ValueError):
        logger.warning(f"[AUDITOR] Ignoring invalid golden asset UUID: {value!r}")
        return None

async def process_asset_with_auditor(asset_id: UUID, is_golden: bool, db: AsyncSession, trace_id: str) -> bool:
    """
    Fetches all vectors for an asset, and either indexes them (if golden)
    or searches them against the Auditor microservice.
    """
    try:
        # 1. Fetch the correct vector population for this asset role.
        # Golden rows are permanent library data; suspect rows are disposable.
        is_temporary = not is_golden
        frames = []
        for _ in range(30):
            result = await db.execute(
                select(FrameVector)
                .where(
                    FrameVector.asset_id == asset_id,
                    FrameVector.is_temporary.is_(is_temporary),
                )
                .order_by(FrameVector.timestamp)
            )
            frames = result.scalars().all()
            if frames:
                break
            await asyncio.sleep(1.0)

        if not frames:
            storage = "temporary" if is_temporary else "permanent"
            logger.warning(
                f"[AUDITOR] No {storage} vectors found for asset {asset_id} after waiting. Skipping."
            )
            return False

        result_audio = await db.execute(
            select(AudioSegment)
            .where(AudioSegment.asset_id == asset_id)
            .order_by(AudioSegment.start_time)
        )
        audio_segments_records = result_audio.scalars().all()

        visual_vectors = []
        text_vectors = []
        audio_vectors = []
        for f in frames:
            if f.visual_vector is not None:
                v_vec = f.visual_vector.tolist() if hasattr(f.visual_vector, "tolist") else f.visual_vector
                visual_vectors.append(v_vec)
            if f.text_vector is not None:
                t_vec = f.text_vector.tolist() if hasattr(f.text_vector, "tolist") else f.text_vector
                text_vectors.append(t_vec)

        # Send audio segments if needed, though they might not be vectors, they are audio data.
        # If the ML Auditor expects "audio_vectors", we can send the raw texts or if they have vectors, we send those.
        for a in audio_segments_records:
            # Audio vectors are not currently generated by Whisper/Vision node,
            # so we leave audio_vectors empty. But we successfully waited for the segments to commit.
            pass

        payload = {
            "asset_id": str(asset_id),
            "visual_vectors": visual_vectors,
            "text_vectors": text_vectors,
            "audio_vectors": audio_vectors
        }

        # 2. Communicate with Auditor microservice.
        # Golden assets are indexed into FAISS; suspect assets search FAISS and
        # persist only the verdict/result row in Postgres.
        async with httpx.AsyncClient() as client:
            if is_golden:
                logger.info(f"[AUDITOR] Sending golden asset {asset_id} to /index endpoint. trace={trace_id}")
                resp = await client.post(f"{AUDITOR_URL}/index", json=payload, timeout=30.0)
                resp.raise_for_status()
                logger.info(f"[AUDITOR] Golden asset {asset_id} indexed successfully.")
                return True
            else:
                logger.info(f"[AUDITOR] Sending suspect asset {asset_id} to /search endpoint. trace={trace_id}")
                resp = await client.post(f"{AUDITOR_URL}/search", json=payload, timeout=30.0)
                resp.raise_for_status()

                search_data = resp.json()
                verdict = search_data.get("verdict", "CLEAN")
                if verdict == "THREAT":
                    verdict = "PIRACY_DETECTED"
                fused_score = search_data.get("fused_score", 0.0)
                visual_score = search_data.get("visual_score", fused_score)
                text_score = search_data.get("text_score", 0.0)
                golden_asset_id = _uuid_or_none(
                    search_data.get("golden_asset_id") or search_data.get("matched_asset_id")
                )
                matched_timestamp = search_data.get("matched_timestamp")

                logger.info(f"[AUDITOR] Search complete for {asset_id}. Verdict={verdict}, Score={fused_score:.2f}")

                stmt = pg_insert(SimilarityResult).values(
                    suspect_asset_id=asset_id,
                    golden_asset_id=golden_asset_id,
                    matched_timestamp=matched_timestamp,
                    visual_score=visual_score,
                    text_score=text_score,
                    fused_score=fused_score,
                    verdict=verdict,
                ).on_conflict_do_update(
                    index_elements=[SimilarityResult.suspect_asset_id],
                    set_={
                        "golden_asset_id": golden_asset_id,
                        "matched_timestamp": matched_timestamp,
                        "visual_score": visual_score,
                        "text_score": text_score,
                        "fused_score": fused_score,
                        "verdict": verdict,
                    },
                )
                await db.execute(stmt)
                purge_result = await db.execute(
                    delete(FrameVector).where(
                        FrameVector.asset_id == asset_id,
                        FrameVector.is_temporary.is_(True),
                    )
                )
                await db.commit()
                logger.info(
                    f"[AUDITOR] Purged {purge_result.rowcount or 0} temporary vectors "
                    f"for suspect asset {asset_id}. trace={trace_id}"
                )
                return True

    except Exception as exc:
        logger.error(f"[AUDITOR] Error communicating with ML Auditor: {exc!r} trace={trace_id}")
        await db.rollback()
        return False
